### ISSUE TITLE
Unrecognized option: --data-urlencode

### ISSUE THREAD

**Issue by Kerooker** [libetl/curl#1]
When I try to use --data-urlencode I get an UnrecognizedOption: --data-urlencode.

What should be done about it?

`$("curl --data-urlencode \"model\" www.google.com");`
Reproduceable example

**Comment by libetl** [comment]
Hi,
interesting example.
Will have a look.

**Comment by Kerooker** [comment]
Thanks! 
Also happens to `curl --version`

**Comment by libetl** [comment]
Will continue my dig into this issue in a few hours.
Will try to implement what is described there : https://curl.haxx.se/docs/manpage.html

**Comment by libetl** [comment]
Please have a look at the new unit test : 
https://github.com/libetl/curl/blob/master/src/test/java/org/toilelibre/libe/outside/curl/CurlTest.java#L194

Is it what you were waiting for ?

Thanks.

**Comment by Kerooker** [comment]
Perfect. Thanks!
Any bitcoin address?

**Comment by libetl** [comment]
I do that for free. My pleasure.

**Comment by libetl** [comment]
Wait this evening until I deploy 0.0.10
