### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ShafiqSadat** [libetl/curl#10]
any way to download and save file in one line 

ex : $("curl http://dl.sourcebaran.com/download/462/javadb-desktop-applications_SourceBaran.Com.rar"@"C://Downloads");

**Comment by libetl** [comment]
Hi,

the -o parameter is the one you need

here is my unit test : 

```java
    @Test
    public void outputFile () {
        File file = new File("target/classes/downloadedCurl");

        boolean fileDeleted = file.delete();
        LOGGER.log(Level.FINE, "output file deleted : " + fileDeleted);
        this.assertOk (this.curl ("-k -E src/test/resources/clients/libe/libe.pem -X GET -A 'toto' -H 'Accept: */*' -H 'Host: localhost' 'https://localhost:%d/public' -o target/classes/downloadedCurl"));
        Assert.assertTrue (new File ("target/classes/downloadedCurl").exists ());
    }
```

source : https://github.com/libetl/curl/blob/master/src/test/java/org/toilelibre/libe/outside/curl/CurlTest.java

**Comment by ShafiqSadat** [comment]
Sorry im new in java 
its correct?

$("curl http://dl.sourcebaran.com/download/462/javadb-desktop-applications_SourceBaran.Com.rar"+ -o C://Downloads");

😭

**Comment by libetl** [comment]
try this : 

```
$("curl http://dl.sourcebaran.com/download/462/javadb-desktop-applications_SourceBaran.Com.rar -o C://Downloads");
```

**Comment by ShafiqSadat** [comment]
Worked Thanks !
