### ISSUE TITLE
StackOverflowError on POST with large json data

### ISSUE THREAD

**Issue by antracs99** [libetl/curl#19]
Version 0.019

**Describe the bug**
HttpResponse response = curl(fileContent); 
throws
org.toilelibre.libe.curl.Curl$CurlException: java.util.concurrent.ExecutionException: java.lang.StackOverflowError

**Environment**
Special configuration in /etc/hosts ? No
Reverse proxy ? No
VPN ? N
Proxy ? N

**Curl command line**
localhost:9200 is ElasticSearch REST API endpoint
curl -X POST "http://localhost:9200/default_ddcm/ApplicationProfile/m683592e896e4d32b086c3468252fe55/_update" -H 'Content-Type: application/json' --data-binary '
{
   "doc" : {
        "termsOfReference" : "Termeni \u0219i conditii de utilizare a serviciului Asigno\r\nServiciul Asigno este pus la dispozi\u021Bia utilizatorilor de c\u0103tre PHOENIX-IT SRL, av\u00E2nd sediul social  \u00EEn   Str. Colonel Ion Buzoianu, Nr. 20A, Bra\u0219ov, Cod 500084. Compania este \u00EEnregistrat\u0103 la Registrul Comer\u021Bului din Romania sub nr. J08\/1576\/2004 , CUI RO16578664 .\r\n\r\nAsigno permite Liber Profesioni\u0219tilor s\u0103 \u00EE\u0219i expun\u0103 \u00EEn mod electronic serviciile prestate c\u0103tre Cet\u0103\u021Beni.\r\n\r\nAsigno permite Cet\u0103\u021Benilor s\u0103 acceseze serviciile oferite de c\u0103tre Liber Profesioni\u0219ti, prin Internet, 24 de ore din 24, 7 zile din 7, din orice col\u021B al lumii.\r\n\r\nAsigno permite:\r\n\r\nColaborarea \u00EEntre Cet\u0103\u021Beni \u0219i Liber Profesioni\u0219ti;\r\n\u00CEnc\u0103rcarea securizat\u0103 de c\u0103tre Cet\u0103\u021Beni a documentelor scanate aferente serviciilor efectuate de c\u0103tre Liber Profesioni\u0219ti;\r\n\u00CEnc\u0103rcarea securizat\u0103 de c\u0103tre Liber Profesioni\u0219ti a documentelor aferente serviciilor efectuate;\r\nVizualizarea de c\u0103tre Cet\u0103\u021Beni \u0219i Liber Profesioni\u0219ti a portofoliului de solicit\u0103ri;\r\nVizualizarea statusului solicit\u0103rilor \u00EEn desf\u0103\u0219urare;\r\nGestionarea calendarului de \u00EEnt\u00E2lniri dintre Cet\u0103\u021Beni \u0219i Liber Profesioni\u0219ti.\r\n\r\n\r\n1. \u00CENREGISTRAREA UTILIZATORULUI CET\u0102\u021AEAN\r\nPentru accesarea serviciilor de c\u0103tre Cet\u0103\u021Beni este necesar ca utilizatorul s\u0103 \u00EE\u0219i creeze un cont. Dup\u0103 ce cet\u0103\u021Beanul s-a \u00EEnregistrat \u00EEn aplica\u021Bia mobila sau \u00EEn cea web, el poate apela la serviciile Liber Profesioni\u0219tilor. \r\nContul de utilizator se acceseaz\u0103 printr-un nume de utilizator \u0219i parol\u0103 sau folosind serviciile de identitate social\u0103 ale Google (doar pentru aplica\u021Bia web) \u0219i Facebook.\r\nValidarea \u00EEnregistr\u0103rii se va face de c\u0103tre solicitant prin intermediul contului de email. Validarea este necesar\u0103 doar \u00EEn cazul \u00EEnregistr\u0103rii cu nume de utilizator \u0219i parol\u0103.\r\nUtilizarea este nominal\u0103 \u0219i nu poate fi transferat\u0103 unei alte persoane.\r\n\r\n2. \u00CENREGISTRAREA UTILIZATORULUI LIBER PROFESIONIST\r\nPentru publicarea serviciilor efectuate c\u0103tre Cet\u0103\u021Beni, Liber Profesioni\u0219tii trebuie s\u0103 completeze formularul de \u00EEnregistrare. Odat\u0103 completat formularul, Liber Profesionistul va fi contactat de c\u0103tre personalul PHOENIX-IT SRL \u00EEn vederea \u00EEncheierii unui contract. \u00CEnregistrarea utilizatorului Liber Profesionist va fi finalizat\u0103 de c\u0103tre personalul PHOENIX-IT SRL ulterior semn\u0103rii contractului.\r\n\r\n3. INI\u021AIEREA UNEI SOLICIT\u0102RI\r\nCet\u0103\u021Beanul poate ini\u021Bia o solicitare de efectuare a unui serviciu prestat de c\u0103tre Liber Profesionist prin intermediul aplica\u021Biei mobile sau web urm\u00E2nd pa\u0219i de mai jos:\r\nSelectarea categoriei de servicii;\r\nSelectarea Liber Profesionistului;\r\nSelectarea serviciului;\r\n\u00CEnc\u0103rcarea documentelor necesare efectu\u0103rii serviciului;\r\nExpedierea solicit\u0103rii.\r\nUn reprezentant al Liber Profesionistului selectat, va proceda la analizarea informa\u021Biilor introduse \u00EEn vederea accept\u0103rii sau respingerii cererii. \u00CEn cazul \u00EEn care pentru o solicitarea se constat\u0103 c\u0103 nu sunt furnizate toate detaliile, Liber Profesionistul poate solicita informa\u021Bii suplimentare. \r\nLista de solicit\u0103ri acceptate sau respinse, \u00EEn desf\u0103\u0219urare sau \u00EEncheiate poate fi verificat\u0103 oric\u00E2nd de c\u0103tre Cet\u0103\u021Bean prin intermediul aplica\u021Biei mobile sau web.\r\nOdat\u0103 trimis\u0103 o solicitare c\u0103tre un Liber Profesionist, cet\u0103\u021Beanul se oblig\u0103 s\u0103 pl\u0103teasc\u0103 o taxa de reziliere a solicit\u0103rii. Asigno \u0219i PHOENIX-IT SRL nu interfereaz\u0103 \u00EEn niciun fel \u00EEn rela\u021Biile Cet\u0103\u021Bean \u2013 Liber Profesionist, Asigno pun\u00E2nd la dispozi\u021Bie doar platforma de colaborare. Toate fluxurile financiare vor fi derulate exclusiv \u00EEntre Cet\u0103\u021Bean \u0219i Liber Profesionist.\r\n\r\n4. \u00CENREGISTRAREA UTILIZATORULUI \u2013 CLAUZE GENERALE\r\nUtilizatorul declar\u0103 \u0219i garanteaz\u0103 c\u0103 nici una din informa\u021Biile \u0219i documentele furnizate \u00EEn serviciul Asigno nu con\u021Bin date false, nereale sau omisiuni, cu privire la aspecte esen\u021Biale necesare a fi comunicate.\r\n\r\nPHOENIX-IT SRL, \u00EE\u0219i rezerv\u0103 dreptul de a v\u0103 suspenda sau dezactiva conturile de utilizator \u00EEn urm\u0103toarele condi\u021Bii:\r\n\r\nDac\u0103 se constat\u0103 sau exist\u0103 suspiciuni c\u0103 datele de \u00EEnregistrare sunt false, nereale sau con\u021Bin omisiuni esen\u021Biale;\r\nDac\u0103 legisla\u021Bia aplicabil\u0103, autorit\u0103\u021Bile sau instan\u021Bele competente ne solicit\u0103\/impun acest lucru;\r\nDac\u0103 decidem s\u0103 retragem\/\u00EEnchidem serviciul Asigno. PHOENIX-IT SRL, nu va fi r\u0103spunz\u0103tor pentru eventuale implica\u021Bii ale unei astfel de decizii.\r\nPHOENIX-IT SRL, \u00EE\u021Bi rezerv\u0103 dreptul (nu \u0219i obliga\u021Bia) de a verifica autenticitatea datelor de \u00EEnregistrare ale utilizatorilor. Prin acceptarea Termenilor \u0219i Condi\u021Biilor, utilizatorul \u00EE\u0219i exprim\u0103 acordul pentru eventualele verific\u0103ri ce vor fi efectuate de PHOENIX-IT SRL, pentru verificarea exactit\u0103\u021Bii datelor furnizate.\r\n\r\n5. MODIFIC\u0102RILE SERVICIULUI\r\nPHOENIX-IT SRL \u00EE\u0219i rezerv\u0103 dreptul de a modifica sau \u00EEntrerupe, temporar sau permanent serviciul Asigno. \u00CEn acest caz, PHOENIX-IT SRL nu este r\u0103spunz\u0103tor fa\u021B\u0103 de utilizatori sau fa\u021B\u0103 de o ter\u021B\u0103 persoana pentru orice modificare, suspendare sau \u00EEntrerupere a serviciilor disponibile prin intermediul platformei Asigno.\r\n\r\n6. LIMITELE R\u0102SPUNDERII\r\nUtilizatorul accept\u0103 \u00EEn mod expres c\u0103 PHOENIX-IT SRL nu va fi r\u0103spunz\u0103tor pentru nici un fel de daune sau prejudicii directe, indirecte, accidentale, speciale, inclusiv, dar f\u0103r\u0103 a se limita la prejudicii const\u00E2nd \u00EEn pierdere de profit, imposibilitatea de folosire, date sau alte pierderi intangibile sau incomensurabile, rezult\u00E2nd din:\r\n\r\nDatele furnizate de c\u0103tre PHOENIX-IT SRL, prin intermediul platformei Asigno;\r\nUtilizarea defectuoas\u0103 sau imposibilitatea utiliz\u0103rii platformei Asigno;\r\nAccesul neautorizat la datelor utilizatorului;\r\nDeclara\u021Bii sau ac\u021Biuni ale unei ter\u021Be p\u0103r\u021Bi asupra platformei Asigno;\r\nOrice alt\u0103 problem\u0103 legat\u0103 de platforma Asigno;\r\n7. NOTIFIC\u0102RI \u0218I COMUNIC\u0102RI\r\nNotific\u0103rile sau comunic\u0103rile adresate utilizatorilor vor fi f\u0103cute pe cale electronic\u0103. Asigno poate face notific\u0103ri privind schimbarea Termenilor \u0219i Condi\u021Biilor sau alte chestiuni prin afi\u0219area de \u00EEn\u0219tiin\u021B\u0103ri c\u0103tre utilizatori \u00EEn mod general, pe site-ul serviciului, sau \u00EEn aplica\u021Bia mobil\u0103 sau web.\r\n\r\n8. POLITICA DE SECURITATE \u0218I PROTEC\u021AIA DATELOR CU CARACTER PERSONAL\r\nPHOENIX-IT SRL prelucreaz\u0103 date caracter personal \u00EEn scopul oferirii de servicii specifice privind Profesiile Liberale (Exemplu: notari, avoca\u021Bi, etc.), la solicitarea clien\u021Bilor no\u0219tri, asigur\u00E2ndu-ne de respectarea obliga\u021Biilor legale prev\u0103zute de Regulamentul (UE) 2016\/679 privind protec\u021Bia persoanelor fizice \u00EEn ceea ce prive\u0219te prelucrarea datelor cu caracter personal \u0219i privind libera circula\u021Bie a acestor date \u0219i de abrogare a Directivei 95\/46\/CE (GDPR), precum \u0219i respectarea cerin\u021Belor legale prev\u0103zute de legisla\u021Bia na\u021Bional\u0103 din domeniul de referin\u021B\u0103.\r\n\r\nPHOENIX-IT SRL cunoa\u0219te importan\u021Ba datelor dvs. personale si se angajeaz\u0103 s\u0103 protejeze confiden\u021Bialitatea \u0219i securitatea acestora \u0219i garanteaz\u0103 ca datele cu caracter personal vor fi prelucrate cu bun\u0103-credin\u021B\u0103 \u0219i \u00EEn conformitate cu dispozi\u021Biile legale \u00EEn vigoare. Acest angajament nu se aplica \u0219i in cazul informa\u021Biilor dezv\u0103luite deliberat de c\u0103tre utilizator unor p\u0103r\u021Bi ter\u021Be (ex. de c\u0103tre persoanele fizice c\u0103rora li se furnizeaz\u0103 servicii notariale).\r\n\r\nDe aceea, este important pentru noi s\u0103 v\u0103 furniz\u0103m \u00EEntr-o form\u0103 inteligibil\u0103 \u0219i u\u0219or accesibil\u0103 toate informa\u021Biile legate de prelucrarea datelor dvs. cu caracter personal, efectuat\u0103 de compania noastr\u0103, av\u00E2nd \u00EEn vedere calitatea dumneavoastr\u0103 de utilizator al platformei Asigno , precum \u0219i de persoan\u0103 vizat\u0103 (clien\u021Bi, poten\u021Biali clien\u021Bi, vizitatori site, notari etc.).\r\n\r\n\u00CEn acest context, va rugam sa parcurge\u021Bi aceasta politica \u0219i, \u00EEn situa\u021Bia \u00EEn care aprecia\u021Bi c\u0103 informa\u021Biile prezentate aici nu sunt suficient de explicite pentru dumneavoastr\u0103, v\u0103 rug\u0103m s\u0103 ne adresa\u021Bi orice \u00EEntrebare la datele de contact men\u021Bionate mai jos:\r\n\r\nPHOENIX-IT SRL;\r\nSediul social: Str. Colonel Ion Buzoianu, Nr. 20A, Bra\u0219ov, Cod 500084;\r\nRegistrul Comer\u021Bului: J08\/1576\/2004;\r\nC.U.I. RO16578664;\r\nTelefon: +40 371 175 116;\r\nE-Mail: security@asigno.ro;\r\n8.1. CUM COLECT\u0102M DATELE CU CARACTER PERSONAL CARE V\u0102 PRIVESC? CARE ESTE SCOPUL ACESTEI PRELUCR\u0102RI?\r\nV\u0103 inform\u0103m c\u0103  PHOENIX-IT SRL administreaz\u0103 datele cu caracter personal pe care ni le furniza\u021Bi \u00EEn condi\u021Bii de siguran\u021Ba \u0219i numai pentru scopurile utiliz\u0103rii serviciului Asigno. Datele dumneavoastr\u0103 sunt colectate astfel:\r\n\r\n\u00CEn aplica\u021Biile aferente serviciului Asigno, acolo unde sunt necesare pentru \u00EEnregistrarea dumneavoastr\u0103 ca utilizator al serviciului. Pentru a facilita aceast\u0103 \u00EEnregistrarea \u0219i pentru a limita prelucrarea datelor personale care v\u0103 privesc (ex. pentru a evita o dubl\u0103 colectare de date personale), la op\u021Biunea dumneavoastr\u0103, datele personale vor fi preluate de la un operator ter\u021B de identitate social\u0103(Facebook sau Google). Categoriile de date personale preluate de la ace\u0219ti operatori sunt cele disponibile \u00EEn profilul de utilizator al aplica\u021Biei Asigno \u0219i ne sunt necesare pentru a v\u0103 furniza accesul punctual \u0219i personalizat la serviciile solicitate. \u00CEn situa\u021Bia \u00EEn care nu dori\u021Bi s\u0103 v\u0103 introduce\u021Bi datele personale \u00EEn sec\u021Biunea de \u00EEnregistrare utilizatori, ve\u021Bi putea \u00EEn continuare s\u0103 utiliza\u021Bi site-ul nostru de informare general\u0103.\r\n\u00CEn aplica\u021Biile aferente serviciului Asigno, dup\u0103 autentificarea dvs. \u0219i INI\u021AIEREA UNEI SOLICIT\u0102RI (vezi sec\u021Biunea), va trebui s\u0103 \u00EEnc\u0103rca\u021Bi, dup\u0103 caz, documentele necesare pentru serviciul selectat de dumneavoastr\u0103. V\u0103 inform\u0103m c\u0103 documentele respective sunt necesare Liber Profesionistului pentru furnizarea serviciului solicitat de dumneavoastr\u0103, iar legalitatea \u0219i necesitatea acestei prelucr\u0103ri de date personale revine acestuia. Obliga\u021Bia care ne revine, \u00EEn acest caz, este de a prelua documentele \u00EEnc\u0103rcate de dumneavoastr\u0103 \u00EEn aplica\u021Biile Asigno \u0219i de a le pune la dispozi\u021Bia Liber Profesionistului selectat, \u00EEn condi\u021Bii de siguran\u021B\u0103.\r\nPHOENIX-IT SRL prelucreaz\u0103 datele personale ale utilizatorului, \u00EEn temeiul legii, cu bun\u0103-credin\u021B\u0103, \u00EEn scopuri legitime, pentru furnizarea serviciilor selectate \u0219i furnizate de ter\u021Bii Liber Profesioni\u0219ti prin intermediul platformei Asigno.\r\n\r\nPrin \u00EEnregistrarea contului de utilizator \u0219i prin acceptarea Politicii de confiden\u021Bialitate, va exprimati acordul la prelucrarea datelor cu caracter personal de c\u0103tre PHOENIX-IT SRL, \u00EEn conformitate cu prevederile GDPR.\r\n\r\nDaca nu sunte\u021Bi de acord ca datele sa v\u0103 fie prelucrate de c\u0103tre noi, ave\u021Bi dreptul si libertatea de a nu crea contul de utilizator si de a nu utiliza serviciile aferente.\r\n\r\nPreciz\u0103m c\u0103 nu exist\u0103 un proces decizional automatizat incluz\u00E2nd crearea de profiluri, a\u0219a cum este men\u021Bionat la articolul 22 alineatele (1) \u0219i (4) din GDPR.\r\n\r\n8.2. TEMEIUL JURIDIC AL PRELUCR\u0102RII DATELOR\r\nV\u0103 inform\u0103m c\u0103 datele cu caracter personal care v\u0103 privesc sunt prelucrate de c\u0103tre PHOENIX-IT SRL pe baza consim\u021B\u0103m\u00E2ntului liber exprimat de dumneavoastr\u0103, \u00EEn sec\u021Biunea de \u00EEnregistrare utilizator \u0219i la ini\u021Bierea unei solicit\u0103ri. Prin acest consim\u021B\u0103m\u00E2nt, sunte\u021Bi de acord s\u0103 prelucr\u0103m urm\u0103toarele date personale:\r\n\r\nDatele introduse de dvs. sau preluate de la un operator ter\u021B de identitate social\u0103 (Google sau Facebook) pentru crearea contului de acces;\r\nDatele personale con\u021Binute \u00EEn documentele necesare pentru prestarea serviciilor de c\u0103tre Liber Profesioni\u0219tii pe care dumneavoastr\u0103 i-a\u021Bi selectat;\r\nDatele personale introduse de dumneavoastr\u0103 \u00EEn aplica\u021Biile Asigno;\r\nAlte date personale care rezult\u0103 din finalizarea unui serviciu prestat de un Liber Profesionist.\r\nV\u0103 inform\u0103m c\u0103, \u00EEn orice moment, ave\u021Bi dreptul de a v\u0103 retrage consim\u021B\u0103m\u00E2ntul privind prelucrarea datelor care v\u0103 apar\u021Bin, f\u0103r\u0103 a afecta legalitatea prelucr\u0103rii efectuate pe baza consim\u021B\u0103m\u00E2ntului \u00EEnainte de retragerea acestuia. Retragerea consim\u021B\u0103m\u00E2ntului se face prin completarea formularului aferent din sec\u021Biunea GDPR a www.asigno.ro sau prin transmiterea unui email la security@asigno.ro.\r\n\r\n\u00CEn aceast\u0103 situa\u021Bie datele dumneavoastr\u0103 personale vor fi \u0219terse din eviden\u021Ba noastr\u0103 \u0219i orice prelucrare a acestora va \u00EEnceta.\r\n\r\n8.3. SECURITATEA PRELUCR\u0102RILOR DE DATE PERSONALE\r\nV\u0103 asigur\u0103m c\u0103, pentru prelucrarea datelor personale care v\u0103 privesc, PHOENIX-IT SRL a alocat toate resursele necesare \u0219i disponibile \u00EEn vederea implement\u0103rii unor m\u0103suri tehnice \u0219i organizatorice adecvate pentru a asigura confiden\u021Bialitatea, integritatea \u0219i disponibilitatea acestor date, dintre care amintim: \r\n\u2022 Servicii criptate de conexiune la site;\r\n\u2022 Echipamente de securizare a accesului la re\u021Bea;\r\n\u2022 Componente specifice de protec\u021Bie anti-virus, anti-malware; \r\n\u2022 Aplicarea regulat\u0103 de actualiz\u0103ri pentru infrastructura software \u0219i hardware implicat\u0103;\r\n\u2022 Instruirea persoanelor care administreaz\u0103 aplica\u021Bia cu privire la responsabilit\u0103\u021Bile \u0219i obliga\u021Biile pe care le au \u00EEn vederea asigur\u0103rii securit\u0103\u021Bii adecvate a prelucr\u0103rilor de date;\r\n\u2022 Acces restric\u021Bionat la date;\r\n\u2022 Testare periodic\u0103 a eficien\u021Bei m\u0103surilor de securitate aplicate.\r\n\r\n8.4. INFORMA\u021AII REFERITOARE LA STOCAREA DATELOR PERSONALE\r\nToate informa\u021Biile personale pe care le trimite\u021Bi prin intermediul serviciului Asigno, sunt p\u0103strate pe servere securizate, localizate \u00EEn data center-ul PHOENIX-IT SRL. Datele introduse de dumneavoastr\u0103 pot fi accesate de c\u0103tre Liber Profesioni\u0219tii selecta\u021Bi pentru a v\u0103 oferii serviciile solicitate. \r\nDurata de stocare a datelor personale care v\u0103 privesc este:\r\n\u2022 Pentru datele furnizate de dvs. pentru \u00EEnregistrarea pe site, datele vor fi p\u0103strate p\u00E2n\u0103 \u00EEn momentul \u00EEn care ve\u021Bi solicita \u00EEntreruperea serviciului din sec\u021Biunea GDPR.\r\n\u2022 Pentru solicit\u0103rile de servicii din partea Liber Profesioni\u0219tilor, durata de p\u0103strare este de 12 luni de la finalizarea serviciului. Termenul a fost ales pentru a pune la dispozi\u021Bia dumneavoastr\u0103 o perioad\u0103 rezonabil\u0103 pentru a putea accesa \u0219i a desc\u0103rca documentele eferente serviciilor prestate de c\u0103tre Liber Profesioni\u0219ti.\r\n\r\n8.5. CE DREPTURI DE ACCES AVETI\r\nLa solicitarea dumneavoastr\u0103 transmis\u0103 prin email, prin po\u0219t\u0103 sau prin completarea c\u00E2mpurilor aferente din sec\u021Biunea GDPR a www.asigno.ro, pute\u021Bi solicita, cu titlu gratuit, urm\u0103toarele informa\u021Bii sau ac\u021Biuni:\r\n\r\nDreptul de a fi informat. Dac\u0103 dori\u021Bi \u0219i alte informa\u021Bii referitoare la prelucrarea datelor personale, \u00EEn afara celor precizate aici, v\u0103 rug\u0103m s\u0103 ne transmite\u021Bi o solicitare \u00EEn acest sens.\r\nDreptul de acces la datele care v\u0103 privesc, respectiv prin confirmarea prelucr\u0103rii datelor personale si, dup\u0103 caz, furnizarea de informa\u021Bii referitoare la: categoriile de date prelucrate, scopul prelucr\u0103rii, posibili destinatari, durata de stocare, interesul legitim, precum \u0219i informa\u021Bii referitoare la drepturile dumneavoastr\u0103.\r\nDreptul la rectificarea datelor, \u00EEn situa\u021Bia \u00EEn care considera\u021Bi c\u0103 acestea sunt incorecte sau incomplete (inclusiv prin furnizarea unei declara\u021Bii suplimentare).\r\nDreptul de \u0219tergere (dreptul de a fi uitat), presupune \u0219tergerea datelor cu caracter personal care v\u0103 privesc, f\u0103r\u0103 \u00EEnt\u00E2rzieri nejustificate.\r\nDreptul de a restric\u021Biona procesarea pentru o perioad\u0103 limitat\u0103, sens \u00EEn care trebuie s\u0103 ne solicita\u021Bi perioada pentru care vre\u021Bi s\u0103 v\u0103 fie restric\u021Bionat\u0103 prelucrarea datelor dvs., \u0219i dup\u0103 caz, motivul acestei solicit\u0103ri.\r\nDreptul la portabilitatea datelor, respectiv dreptul de a primi datele cu caracter personal care v\u0103 privesc \u0219i pe care le-a\u021Bi furnizat operatorului \u00EEntr-un format structurat, utilizat \u00EEn mod curent \u0219i care poate fi citit automat \u0219i dreptul de a transmite aceste date altui operator.\r\nDreptul la opozi\u021Bie, respectiv dreptul de a v\u0103 opune, \u00EEn orice moment, la prelucrarea datelor personale care v\u0103 privesc. V\u0103 amintim c\u0103 acest drept poate fi materializat imediat, prin retragerea consim\u021B\u0103m\u00E2ntului dumneavoastr\u0103, potrivit celor men\u021Bionate \u00EEn prezentul document. De asemenea, v\u0103 inform\u0103m c\u0103 ave\u021Bi dreptul de a v\u0103 opune, \u00EEn orice moment, la activit\u0103\u021Bile de marketing direct efectuate de PHOENIX-IT SRL cu datele dumneavoastr\u0103 personale.\r\nDreptul de nu face parte la un proces decizional individual automatizat, inclusiv prin crearea de profiluri. V\u0103 inform\u0103m c\u0103 PHOENIX-IT SRL nu desf\u0103\u0219oar\u0103 procese decizionale automatizate care s\u0103 vizeze aspecte personale ale dvs.\r\n\u00CEn situa\u021Bia \u00EEn care considera\u021Bi ca v-au fost \u00EEnc\u0103lcate drepturile legale men\u021Bionate anterior, v\u0103 inform\u0103m c\u0103 ave\u021Bi dreptul de a v\u0103 adresa \u00EEn instan\u021B\u0103 sau de a adresa o pl\u00E2ngere la Autoritatea de Supraveghere a Prelucr\u0103rilor de Date cu Caracter Personal.\r\n\r\nPentru orice alte informa\u021Bii \u00EEn leg\u0103tur\u0103 cu exercitarea acestor drepturi, v\u0103 rug\u0103m s\u0103 ne contacta\u021Bi.\r\n\r\n8.6. TRANSMITEREA C\u0102TRE TER\u021AI A DATELOR PERSONALE\r\nV\u0103 inform\u0103m c\u0103 datele cu caracter personal care v\u0103 privesc nu sunt transferate c\u0103tre alte state sau c\u0103tre al\u021Bi destinatari, persoane fizice\/sau juridice, cu excep\u021Bia Liber Profesioni\u0219tilor selecta\u021Bi de c\u0103tre dumneavoastr\u0103 care, pe baza acestor informa\u021Bii, v\u0103 pot furniza serviciile solicitate.\r\n\r\nDe asemenea, v\u0103 inform\u0103m c\u0103, potrivit obliga\u021Biilor legale pe care le avem \u0219i c\u00E2nd ne este solicitat acest lucru, putem furniza datele dumneavoastr\u0103 c\u0103tre autorit\u0103\u021Bi publice investite cu atribu\u021Bii specifice (Parchet, Politie, instan\u021Bele judec\u0103tore\u0219ti \u0219i altor organe abilitate ale statului), \u00EEn baza \u0219i \u00EEn limitele prevederilor legale \u0219i ca urmare a unor cereri expres formulate.\r\n\r\nDe\u0219i luam masurile necesare pentru a proteja informa\u021Biile cu caracter personal pe care ni le furniza\u021Bi, preciz\u0103m c\u0103 transmiterea de informa\u021Bii prin intermediul re\u021Belei publice Internet nu poate fi garantat\u0103 drept sigur\u0103 (exist\u0103 conexiuni de re\u021Bea intermediare care nu se afl\u0103 sub controlul nostru, cum ar fi furnizorul local de servicii de comunica\u021Bie). \u00CEn consecin\u021B\u0103, v\u0103 rugam s\u0103 lua\u021Bi \u00EEn considerare c\u0103 nu putem garanta securitatea niciunor informa\u021Bii cu caracter personal pe care ni le transmite\u021Bi prin intermediul Internetului.\r\n\r\n8.7. COLECTAREA AUTOMATA DE DATE CU CARACTER NON-PERSONAL\r\n\u00CEn unele cazuri, este posibil ca PHOENIX-IT SRL s\u0103 colecteze informa\u021Bii cu caracter non-personal despre utilizatori. Exemple de informa\u021Bii de acest tip sunt: tipul de browser folosit, sistemul de operare al calculatorului folosit \u0219i numele domeniului website-ului de unde a fost f\u0103cut\u0103 conexiunea la aplica\u021Bie.\r\n\r\n\u00CEn timpul utiliz\u0103rii aplica\u021Biei PHOENIX-IT SRL va putea stoca anumite informa\u021Bii despre Utilizator. Aceste informa\u021Bii vor fi sub forma unui fi\u0219ier \u201CCookie\u201D sau a unui fi\u0219ier similar. Aceste fi\u0219iere \u201CCookies\u201D ajut\u0103 PHOENIX-IT SRL s\u0103 construiasc\u0103 o aplica\u021Bie care s\u0103 r\u0103spund\u0103 c\u00E2t mai bine intereselor \u0219i preferin\u021Belor utilizatorilor.\r\n\r\nCum \u00EEn cele mai multe browsere de Internet se pot \u0219terge sau bloca fi\u0219ierele \u201ECookies\u201D sau se poate primi o aten\u021Bionare \u00EEnaintea primirii unui astfel de fi\u0219ier, PHOENIX-IT SRL recomand\u0103 utilizatorilor s\u0103 consulte instruc\u021Biunile browser-ului pentru a afla mai multe informa\u021Bii despre aceste func\u021Bii.\r\n\r\n8.8. ALTE PRECIZ\u0102RI\r\nAv\u00E2nd \u00EEn vedere evolu\u021Bia continu\u0103 a tehnologiilor folosite \u00EEn domeniul IT&C, modificarea sau completarea posibil\u0103 a prevederilor legislative din domeniu, precum \u0219i diversificarea \u00EEn timp serviciilor oferite \u00EEn timp de c\u0103tre PHOENIX-IT SRL, ne rezerv\u0103m dreptul de a adapta aceast\u0103 Politic\u0103 ori de c\u00E2te ori va fi cazul. \u00CEn acest sens, pentru a putea fi la curent cu toate informa\u021Biile referitoare la prelucrarea datelor personale care v\u0103 privesc, v\u0103 recomand\u0103m s\u0103 consulta\u021Bi periodic acest document.\r\n\r\n8.9. CLAUZE FINALE\r\nTermenii \u0219i condi\u021Biile de utilizare reprezint\u0103 acordul par\u021Bilor \u0219i reglementeaz\u0103 folosirea de c\u0103tre utilizatori a aplica\u021Biei mobile sau web. Accesarea \u0219i \u00EEnscrierea datelor dumneavoastr\u0103 \u00EEn aceast\u0103 aplica\u021Bie implic\u0103 acceptarea expres\u0103 \u0219i integral\u0103 a acestor termeni \u0219i condi\u021Bii."
    }
}
'

**Expected behavior**
run curl command

**Stacktrace**
stacktrace is empty []

**Comment by antracs99** [comment]
private static String [] getArgsFromCommand (final String requestCommandWithoutBasename) {
        final String requestCommandInput = requestCommandWithoutBasename.replaceAll ("\\s+-([a-zA-Z0-9])", " -$1 ");
        final Matcher matcher = Arguments.ARGS_SPLIT_REGEX.matcher (requestCommandInput);
        final List<String> args = new ArrayList<> ();
        while (matcher.find ()) {
            args.add (ReadArguments.removeSlashes (matcher.group (1).trim ()));
        }
        return args.toArray (new String [args.size ()]);
    }

the regex is ARGS_SPLIT_REGEX is very complex and has to be simplified. 
Pattern.compile(expression) creates a method that is executed recursively on matcher.find()

Check this article:
https://www.javaworld.com/article/2077757/core-java/optimizing-regular-expressions-in-java.html?page=4

"A note about the StackOverflowError"

**Comment by libetl** [comment]
Hi, 
I tried to reproduce the flexible parsing that is available under curl+bash :

https://regex101.com/r/B5Rga8/16/tests

Can you try optimizing that regex for me ?

**Comment by antracs99** [comment]
unfortunately I am not an regex expert, that's why i found an workaround to that problem:
curl -X POST "http://localhost:9200/default_ddcm/ApplicationProfile/m683592e896e4d32b086c3468252fe55/_update" -H 'Content-Type: application/json' --data-binary @path/to/the/payload,json

and now the regex is applied to a simple data source

**Comment by libetl** [comment]
I did not dare to ask you to isolate the request body in a file because you could have good reasons not to do that, but that is definitely something you can do.

Thanks for the feedback and good luck.
