### ISSUE TITLE
Incorrect detection of POST-request

### ISSUE THREAD

**Issue by yshinkarev** [libetl/curl#2]
I can execute: curl --data-urlencode key=value https://some-url.com
It was POST-request.
Not necessarry use: curl -X POST --data-urlencode key=value https://some-url.com
Because I get in console: Note: Unnecessary use of -X or --request, POST is already inferred.

**Comment by libetl** [comment]
You are right. I will add a unit test then commit a fix

**Comment by libetl** [comment]
Will be released as 0.0.11
