### ISSUE TITLE
Can not upload a file

### ISSUE THREAD

**Issue by JulienBreton** [libetl/curl#26]
**Describe the bug**
The file is not uploaded on the server.
If I run the command in a terminal, the file is uploaded.

**Environment**
Ubuntu
Apache server (localhost)

**Curl command line**
curl("-X POST -F 'fileToUpload=@/home/julien/test/test.txt' http://localhost/upload.php");

**Expected behavior**
The file test.txt is uploaded on the server.

**Stacktrace**
HttpResponse :
HttpResponseProxy{HTTP/1.1 200 OK [Date: Sun, 26 May 2019 20:06:02 GMT, Server: Apache/2.4.29 (Ubuntu), Content-Length: 55, Keep-Alive: timeout=5, max=100, Connection: Keep-Alive, Content-Type: text/html; charset=UTF-8] ResponseEntityProxy{[Content-Type: text/html; charset=UTF-8,Content-Length: 55,Chunked: false]}}

**Comment by libetl** [comment]
Hi,

Thanks for this feedback,
Unfortunately I have no access to a computer this week.
Pull requests are welcome or else you need to wait.

Désolé.
LiBe.

**Comment by libetl** [comment]
Ok I have spotted the problem,
it seems like the file uploaded is sent as a parameter in the curl client, but should stay a file parameter

**Comment by libetl** [comment]
I think I have fixed the problem, with release that right away, you should be able to retest in a few hours with 0.0.32

Merci d'avoir repéré ce problème.

**Comment by libetl** [comment]
Please reply even if it works for you.

**Comment by JulienBreton** [comment]
It works perfectly!

Merci pour ton intervention rapide.

**Comment by libetl** [comment]
Anytime.
