### ISSUE TITLE
Parameter with space in POST-request

### ISSUE THREAD

**Issue by yshinkarev** [libetl/curl#3]
I can set header with spaces: --header "Token: aaaa". It works properly.
But if I use parameter: --data-urlencode datetime="2017-05-24 18:02:42", I get error.
Because your function getArgsFromCommand split date and time to 2 arguments.
I try  --data-urlencode datetime='2017-05-24 18:02:42', no success too.

**Comment by libetl** [comment]
Hi @yshinkarev 
Here is the regex I will try to setup in the library : https://regex101.com/r/B5Rga8/15 (have a look at the unit tests)
Is the regular expression correct ?
Thanks for your help.

**Comment by yshinkarev** [comment]
I change datetime="2017-05-24 18:02:42" to "datetime=2017-05-24 18:02:42".
Start works properly.
