### ISSUE TITLE
Some help please.

### ISSUE THREAD

**Issue by baxandrei** [libetl/curl#34]
How I can get body of curl request as String to output in console?
I tried this:
 `$("curl https://localhost:8443/public/");`  but it gives me an error.
![image](https://user-images.githubusercontent.com/12484505/73786187-77985480-47a1-11ea-8a5d-793c765317fc.png)

**Comment by libetl** [comment]
Hello @baxandrei 

ClassNotFoundException is meaningful : the library is not present.

Curl library is either not in your bundled jar or in your target folder.

You need to verify how the project is built. Alternatively, you can try to copy manually the curl jar in your target.


Good luck.

**Comment by baxandrei** [comment]
![image](https://user-images.githubusercontent.com/12484505/74039689-f3c1b080-49ca-11ea-974e-8c908cce7b6f.png)
![image](https://user-images.githubusercontent.com/12484505/74039716-fde3af00-49ca-11ea-8a79-3076a5cb696a.png)

**Comment by libetl** [comment]
provided scope is dangerous.

It means that the jar is not bundled and will need to be provided at runtime by your server or your java options

**Comment by libetl** [comment]
Try compile scope instead

**Comment by baxandrei** [comment]
Thanks!

**Comment by baxandrei** [comment]
Still same problem

**Comment by libetl** [comment]
I don't know how I can help further with that. Can you share the issue with a local expert in your project ?

**Comment by libetl** [comment]
ClassNotFoundException literally means that the classes are not added to your bundled program

**Comment by libetl** [comment]
Which is absolutely not a trouble with the lib itself

**Comment by baxandrei** [comment]
I understand. i will open a ticket on the eclipse forum. Thank you very much.
