### ISSUE TITLE
Option --proxy-user / -U option doesn't work

### ISSUE THREAD

**Issue by ismaeluribepachon** [libetl/curl#9]
org.toilelibre.libe.curl.Curl$CurlException: java.util.concurrent.ExecutionException: org.toilelibre.libe.curl.Curl$CurlException: org.apache.commons.cli.UnrecognizedOptionException: Unrecognized option: --proxy-user

Can you add it?

**Comment by libetl** [comment]
Hello, good idea, But I will need to add several options and to parse the proxy format accurately, that will take some time.

**Comment by libetl** [comment]
Hello,
I have commited a very naive version of the proxy-user argument.

Can you test that "master" version ?

You will find 2 unit tests inside f3979d8. One unit test and one integration test (with a proxy that does not require authentication but which strips out the "Proxy-Authenticate" header.

**Comment by libetl** [comment]
shipped with 0.0.16
